# Change these first
owner: kakik0u # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Kakikou.app
    url: https://kakikou.app
  - name: Bookshelf-Frontend
    url: $BS_F
  - name: Bookshelf-API
    url: $BOOKSHELF_API
  - name: Knet
    url: $KNET
  - name: Knet-API
    url: $KNET_API
  - name: Kexus
    url: $KEXUS
  - name: Solocord
    url: $SC
  - name: ProjectSEKAM
    url: $SEKAM
  - name: KakiContent
    url: $KC
  - name: K-rome
    url: $KROME
  - name: KakikouAuth
    url: $KAKIKOUAUTH
  - name: KakikouLink
    url: $KLINK
  - name: Server-OCI
    url: $OCI
  - name: Server-CB
    url: $CB

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kakikou.app
  # baseUrl: /status
  publish: true
  logoUrl: https://kakikou.app/newkakikoulogo.webp
  name: KakikouAppsStatus
  introTitle: "KakikouApps Status Page"
  introMessage: KakikouAppsの各アプリやサーバーのステータスを確認できます
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
